### ISSUE TITLE
Feature: Remove obsolete consistency checks

### ISSUE THREAD

**Issue by prokolyvakis** [RUrlus/diptest#11]
Hello @RUrlus,

I was considering that since we now moved entirely to C++, we can remove the legacy `ifault` variable and remove some obsolete consistency checks. Specifically, my proposals are the following:

1. Remove completely the `ifault` variable.
2. Create one function `diptst_unsafe` _(func name discussable of course)_ that does not perform the checks for sorting and non negativity. This can save some time when calling either `diptest_pval` or `diptest_pval_mt`.
3. The original function `diptst` will call `diptst_unsafe` while also adding the following code:
```
if (ifault == 1) {
    throw std::runtime_error("N must be >= 1.");
} else if (ifault == 2) {
    throw std::runtime_error("x must be sorted in ascending error.");
}
``` 
(_`ifault` will be removed and the actual checks will be performed in that place_), so the wrapper method can also be refactored a little bit!

WDYT? If you agree, I will be happy to start working on it and create a PR linked to this issue. I am looking forward to your reply!

**Comment by RUrlus** [comment]
Hi @prokolyvakis, that sounds like a great idea. Would be great if you want to pick this up!

**Comment by RUrlus** [comment]
Hi @prokolyvakis, how are you? No worries if not, but have you had the chance to work on this? Otherwise I am going to pick it up. It's a good idea :)

**Comment by prokolyvakis** [comment]
Apologies @RUrlus for the late response. Too much stuff happening recently from my side. I have seen that you have taken handle of this. I have some additional proposals! I will come back when I will find some time! Until then, best regards!

**Comment by RUrlus** [comment]
@prokolyvakis No apologies needed! Looking forward to the other proposals.
