### ISSUE TITLE
Finer resolution for a p-value of 0.0

### ISSUE THREAD

**Issue by greenkidneybean** [RUrlus/diptest#45]
First, thanks for putting together this package! 

I've got a distribution that certainly looks bimodal but I'm getting a p-value of 0.0.  I'm sure the p-value is very low, but not 0.  I'd like to know a more precise threshold for the p-value (e.g. p < 1e-5?).  I'm using diptest-0.7.0 and below is a snippet of code.

```
import diptest 
x = df['my_distribution_data'].values
dip, pval = diptest.diptest(x)
print(dip,pval)
```
Returns: 0.10526623882697403 0.0

**Comment by RUrlus** [comment]
Hi @greenkidneybean, you can have a higher resolution p-value by bootstrapping sufficiently many times. If you want < 1e-5 you'll need to perform more bootstrap iterations, e.g. 1e6 iterations.

`dip, pval = diptest.diptest(x, boot_pval=True, n_boot=int(1e6))`. Note that depending on the size of `x` this can be relatively slow, have a look at the number of threads you'd want to set

**Comment by RUrlus** [comment]
@greenkidneybean Let me know if this didn't solve your issue

**Comment by greenkidneybean** [comment]
@RUrlus Thank you for following up, sorry for the lag on my end.  

I tried your suggestion and I'm still getting a p-value of `0.0`, but since I'm bootstrapping this over 1e6 iterations I should be confident the p-value is <1e-5, yeah?

```
dip, pval = diptest.diptest(x, boot_pval=True, n_boot=int(1e6))
print(f"Dip: {dip} P-value: {pval}")
````
Dip: 0.10526623882697403 P-value: 0.0

**Comment by RUrlus** [comment]
Hi @greenkidneybean, the bootstrapped p-value means that we draw `n_boot` uniform samples of the same length as your input. The p-value is the ratio of samples that had a greater or equal dip statistic than the dip statistic of your input.

A 0.0 p-value for 1e6 iterations means that none of the samples had a higher dip value, this implies that your data is either really multi-modal or that your inputs are not valid.

**What is the data type of your inputs? Note that the test is only valid for continuous distributions!**

Although experimentation has shown that you can use it for integer values if you add uniform noise to it.
We have done this with binned histogram values, e.g. you repeat the bin-center `count` times and add independently sampled uniform(-half BW, half BW).

**Comment by greenkidneybean** [comment]
Hi @RUrlus, thanks again for following-up.  It's a continuous distribution, and just looking by eye it appears bimodal.  The dip test may be overkill but seemed like a way to verify that it's a multi-modal distribution.  It's not a ton of data so I'll paste the array below just for kicks (who doesn't love a dump of text in a closed GitHub issue ;)

```
array([-1.00818321,  6.13767771, -4.34135573,  1.58092061, -1.16439612,
       -3.85223495,  2.21551012,  6.32678398,  6.0474331 ,  5.54927763,
        1.8899803 ,  5.26550453,  5.41416438,  5.21553534,  4.36362263,
        4.88869202,  0.51216121,  5.938545  ,  0.03524716,  6.23116558,
        3.08637513,  6.37570835,  6.01681801,  6.1544915 ,  5.68080302,
        6.02223852,  4.818674  ,  6.05316863,  1.59511573,  6.20407507,
       -0.61481373, -4.33497804, -5.08997231, -4.90891662, -3.66227175,
       -4.94661807,  4.12326262, -4.9265206 ,  1.13119008, -4.67867454,
        3.99038261, -4.88395964,  3.45106156,  4.99682119,  0.51076653,
       -4.02634373,  6.24387557,  4.43580887,  6.12516496, -5.05637887,
       -5.04985056, -5.05452557, -5.12587923, -5.04485422, -5.08743561,
        4.36852345, -4.88543418, -4.8903097 , -4.98999762, -4.55790955,
       -5.07638504, -5.04747607, -4.70567387,  5.72694701,  1.8843483 ,
        4.28256324,  2.29136203,  2.76500893,  3.97793902,  4.44975355,
        1.85695847,  4.83054258,  4.07008531,  4.01419877,  5.03544752,
       -0.89984607,  3.78649469,  6.16200167, -0.80875463, -0.94406571,
        1.25622053,  4.93574831,  5.33068051,  2.26287237,  3.58073375,
       -3.20580455, -4.91219548, -4.30675915, -4.71934981, -3.15135308,
       -4.14731242, -4.66462035, -3.02855699, -3.7619299 , -5.07694099,
       -4.71306617, -5.02101056, -0.76288851, -2.78861921, -4.43218542,
       -4.25153895, -4.95698788,  5.27627818,  4.36568639,  1.94927868,
        2.39315408,  6.28140804,  3.3907641 ,  4.55913312,  5.67759169,
        6.12075857,  5.70705093,  4.46093143,  5.0890965 , -0.42354841,
       -4.84692111,  5.78625059,  2.58218825, -3.08535173, -2.67580497])
 ```

**Comment by RUrlus** [comment]
Yeah that's pretty bimodal. You can safely state the p-value < 1e-5
